import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Frontpage from "./components/frontpage/Frontpage";
import style from "../styles/main/About.module.scss";
import Header from "./components/shared/Header";
import Footer from "./components/shared/Footer";

export default function about() {
  return (
    <>
      <Head>
        <title>Sébastien Legault, Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={style.home}>
        <section className={style.about}>
          {" "}
          <h1 className={style.aboutTitle}>ABOUT ME</h1>
          <article className={style.aboutDescription}></article>
          <p className={style.aboutParagraph}>
            I am a growth-focussed, forward-thinking, bilingual
            (English/French), developer with an eclectic background. I am a
            Registered Holistic Nutritionist, a Red Seal Electrician and
            Self-Taught Developer.
          </p>
          <p className={style.aboutParagraph}>
            I am a Full-Stack Developer with a focus on React. I can work with
            Javascript/Typescript, Node, HTML, CSS/SCSS and Mongo/Mongoose. I
            also have experience with C, AWS and using Jest & Cypress for Unit &
            E2E testing. I am a strong and ambitious learner and can learn
            anything needed to get a task done completely and properly.
          </p>
          <p className={style.aboutParagraph}>
            At my core, I am a people person. I love interacting and helping
            others. I have experience in teaching, training, leading,
            project-planning, customer-service and coordinating with clients.
            During my career as an electrcian, I was the go-to journeyman for
            training new apprentices as I am patient, understanding and
            understand the imptorance of proper training.
          </p>
        </section>
      </main>
      <Footer />
    </>
  );
}
