import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Frontpage from "./components/frontpage/Frontpage";
import Header from "./components/shared/Header";
import Footer from "./components/shared/Footer";
import style from "../styles/main/Contact.module.scss";

export default function contact() {
  return (
    <>
      <Head>
        <title>Sébastien Legault, Full-Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={style.home}>Contact Page</main>
      <Footer />
    </>
  );
}
